# Generated by Django 4.2.7 on 2023-12-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_image_users_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
