# Generated by Django 4.2.7 on 2023-12-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_images_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
